import Head from "next/head";
import Hero from "../src/components/hero";
import KumparanLogo from "../src/assets/kumparan.jpg";
import FeatureCard from "../src/components/featureCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        {/* <FeatureCard /> */}
        <div className="flex flex-col w-full border-opacity-50">
          {/* <div className="grid h-20 card bg-base-300 rounded-box place-items-center">
            content
          </div> */}
          <div className="divider text-4xl font-semibold">Write Platform</div>

          <div className="flex gap-2 p-5 justify-center">
            {" "}
            <div className="card w-96 bg-base-100 shadow-xl image-full">
              <figure>
                <img src={KumparanLogo.src} alt="Shoes" />
              </figure>
              <div className="card-body flex justify-center text-justify w-full">
                <h2 className="card-title">Kumparan</h2>
              </div>
            </div>
            <div className="card w-96 bg-base-100 shadow-xl image-full">
              <figure>
                <img
                  src="https://api.lorem.space/image/shoes?w=400&h=225"
                  alt="Shoes"
                />
              </figure>
              <div className="card-body">
                <h2 className="card-title">Shoes!</h2>
                <p>If a dog chews shoes whose shoes does he choose?</p>
                <div className="card-actions justify-end">
                  <button className="btn btn-primary">Buy Now</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
